### ISSUE TITLE
Модульные тесты

### ISSUE THREAD

**Issue by dmpas** [e8tools/tool1cd#103]
Допилка с датой навела на мысль, что "пора". Пора покрывать модульными тестами подобный функционал, который глазом не проверить.

Накидывайте сюда ссылок на всякие тестовые движки для плюсов, будем выбирать подходящий.

/cc @fishca @andreevlex

**Comment by ava57r** [comment]
**Gogle test**
https://github.com/google/googletest

Short example how to use Google Test with CMake project
https://github.com/snikulov/google-test-examples

Unit-тестирование и C++: что такое mock-объекты на примере Google C++ Mocking Framework
http://artlang.net/article/view/14/

**Comment by ava57r** [comment]
Sample programs for using the Boost.Test unit testing framework 
https://github.com/NigoroJr/boost-test-samples

**Comment by andreevlex** [comment]
Unit-тестирование и C++: что такое mock-объекты на примере Google C++ Mocking Framework
http://artlang.net/article/view/14/

**Comment by ava57r** [comment]
GUnit - GoogleTest/GoogleMock/Cucumber on steroids
https://github.com/cpp-testing/GUnit

**Comment by ava57r** [comment]
CppUnit - The Unit Testing Library
http://cppunit.sourceforge.net/doc/cvs/index.html

**Comment by ava57r** [comment]
CxxTest Unit Testing Framework - http://cxxtest.com
https://github.com/CxxTest/cxxtest

**Comment by artbear** [comment]
Очень крутое 

https://github.com/catchorg/Catch2

A modern, C++-native, header-only, test framework for unit-tests, TDD and BDD - using C++11, C++14, C++17 and later (or C++03 on the Catch1.x branch)

**Comment by dmpas** [comment]
@artbear ты его пробовал?

**Comment by artbear** [comment]
сам еще не пробовал, но читаю записи очень опытного чела (15-20 лет) в С++, который его советует

**Comment by dmpas** [comment]
ну, такие записи наверняка найдутся про каждую из вышеприведённых ссылок :)

**Comment by artbear** [comment]
BDD и TDD одновременно не для каждой будут !

**Comment by fishca** [comment]
дока (https://github.com/catchorg/Catch2/blob/master/docs/tutorial.md#top) выглядит заманчиво, предлагаю опробовать в действии

**Comment by dmpas** [comment]
@fishca попробуй.

**Comment by ava57r** [comment]
В Google Test есть библиотека Google mocking
Помогает эмулировать зависимости, типа как заглушки. Посмотрите есть ли в других такая тема

**Comment by dmpas** [comment]
Впилили Catch2. Спасибо @artbear и всем причастным за наводку.

**Comment by artbear** [comment]
Ага, рад, что удачно зашло.
