### ISSUE TITLE
Не выгружается конфигурация по -dc, -DumpConfig <путь> 

### ISSUE THREAD

**Issue by fishca** [e8tools/tool1cd#128]
Происходит падение на 30-40% прогресса выгрузки из файла 1Cv8.1CD. Возможно это проявление #69

**Comment by dmpas** [comment]
@fishca ты много файлов перепробовал?

**Comment by fishca** [comment]
Пробовал на  больших конфигурациях в основном, возможно в этом дело.

**Comment by dmpas** [comment]
в v8unpack в своё время была проблема, что большие конфиги не разбирались.

**Comment by dmpas** [comment]
@fishca можешь описать подробнее, какую конфу брал и сколько вообще база размером была?

**Comment by fishca** [comment]
[Debug.zip](https://github.com/dmpas/tool1cd/files/1633719/Debug.zip)
Последняя сборка ctool1cd со всеми моими файлами 1Cv8.1CD - БД 1С справилась, как с маленькими так и с большими без проблем. 

Неудачей завершается сохранение конфигурации из файла хранилища 1cv8ddb.1CD. Во вложении файл хранилища и лог

**Comment by fishca** [comment]
Похоже ключ -dc к файлам хранилища не применим и это надо указать в описании команды. 
Для работы с файлом хранилища и выгрузки конфигурации надо использовать -drc

**Comment by dmpas** [comment]
> Похоже ключ -dc к файлам хранилища не применим

именно так и есть. Почему-то мне это было очевидно, если честно

**Comment by ava57r** [comment]
значит что? правим описание и делаем проверку в коде `ай-яй так нельзя` ?

**Comment by dmpas** [comment]
таки я не понял, изначально-то проблема именно в этом и была? что пробовалось `-dc` на базе хранилища? или что?

**Comment by fishca** [comment]
> таки я не понял, изначально-то проблема именно в этом и была? что пробовалось -dc на базе хранилища?

именно так

> правим описание и делаем проверку в коде ай-яй так нельзя ?

я за
