### ISSUE TITLE
Реализовать класс TableRecord

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#129]
Метод `Table::getrecord` возвращает указатель на массив char
Первый байт в массиве предположительно означает удалена запись или нет
`\001` - delete
`\0` - active

Необходим класс, чтобы скрыть это в реализации и не сравнивать каждый раз
`if(*rec)`
`if(!*rec)`
Например как тут:
```c++
rec = new char[t->get_recordlen()];
t->getrecord(nrec, rec);
if(*rec)

table_depot->getrecord(i, rec);
if(!*rec)

table_versions->getrecord(i, rec);
if(*rec) continue;
```
Плюс класс должен скрыть работу и владение массивом char (RAII)

Реализовать методы получения частей записи по `offset` как массив char - аля `bytes(offset, len)`

**Comment by dmpas** [comment]
TableRecord в некотором виде появился.
