### ISSUE TITLE
Исправить hex_to_int(char* hexstr)

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#138]
Проверяются только первые 8 байт, а при использовании передаются массивы до 20 байт
```c++
curlen = hex_to_int(&temp_buf[11]);
start  = hex_to_int(&temp_buf[20]);
```

тут вообще выход за границы массива получается.
```c++
len = hex_to_int(&temp_buf[2]);
```

**Comment by dmpas** [comment]
`char*` надо на `std::string` поменять.

**Comment by ava57r** [comment]
посмотрел по пристальнее =)
нашел ошибку, где ее нет.
везде, где используется в функцию передается указатель на элемент, а не целиком массив.
Тут главное границы массива не проверяются никак.
