### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by dmpas** [e8tools/tool1cd#161]
Надо какую-то установить. Особенно, если гуй будет на Qt - он будет однозначно на GPL.

**Comment by ava57r** [comment]
Ты чаще всего какую используешь?

**Comment by dmpas** [comment]
потому как я в большинстве своём тусуюсь вокруг односкрипта, то применяю MPL2. Но именно тут лично я бы голосовал за GPL.

**Comment by ava57r** [comment]
Ну что GPLv3?

**Comment by dmpas** [comment]
Моё мнение: либа под LGPL, исполняемые части - под GPL. Но тут не только мы должны решать.

**Comment by ava57r** [comment]
> Моё мнение: либа под LGPL, исполняемые части - под GPL. Но тут не только мы должны решать.

поддерживаю LGPL + GPL

**Comment by EvilBeaver** [comment]
Не против
