### ISSUE TITLE
Можно ли при помощи данного форка сбросить пароль Администратора?

### ISSUE THREAD

**Issue by kostakoff** [e8tools/tool1cd#162]
Можно ли при помощи данного форка сбросить пароль Администратора, по аналогии как тут: http://iantonov.me/page/kak-ubrat-parol-polzovatelja-v-1spredprijatie-8 ?

**Comment by dmpas** [comment]
Нет. И графической части у нас пока что тоже нет.

**Comment by Uffik81** [comment]
Надо будет заняться этим делом
