### ISSUE TITLE
TODO: Реализовать GetBufferEncoding

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#174]
#173  - при тестировании выявлена не реализованая функциональность
`TEncoding::GetBufferEncoding` используется в `get_treeFromV8file`

**Comment by ava57r** [comment]
Дока на метод [TEncoding.GetBufferEncoding Method](http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/delphivclwin32/SysUtils_TEncoding_GetBufferEncoding.html)

**Comment by dmpas** [comment]
сам попробуешь или мне запилить по-быстрому?

**Comment by ava57r** [comment]
example source https://github.com/graemeg/freepascal/blob/master/rtl/objpas/sysutils/sysencoding.inc#L206

**Comment by ava57r** [comment]
если ты сегодня запилишь давай =)

**Comment by dmpas** [comment]
@andreevlex там GPL, так что осторожнее, подглядывая код :) мы же ещё не определились с лицензией.

**Comment by dmpas** [comment]
к утру запилю. насчёт "сегодня" не уверен.

**Comment by ava57r** [comment]
Показывать то зачем если трогать нельзя? )

**Comment by dmpas** [comment]
трогать можно, по подцепишь GPL

**Comment by ava57r** [comment]
`подцепишь` звучит не очень)
