### ISSUE TITLE
Неверное владение объектом в SupplierConfigBuilder

### ISSUE THREAD

**Issue by dmpas** [e8tools/tool1cd#208]
тут создаётся уник_птр:
https://github.com/dmpas/tool1cd/blob/develop/src/tool1cd/SupplierConfigBuilder.cpp#L127

тут передаётся владение объектом:
https://github.com/dmpas/tool1cd/blob/develop/src/tool1cd/SupplierConfigBuilder.cpp#L140

уник_птр убивает объект, а новый владелец потом садится в лужу при его использовании.

**Comment by ava57r** [comment]
Согласен.

**Comment by dmpas** [comment]
Проявляется при анализе конфигураций поставщика. Так что можно заодно и тест на это забабахать.

**Comment by ava57r** [comment]
А тут другой вопрос, может стоит подумать о том чтобы переписать V8Catalog на владение потоком переданным ему в конструкторе?
Не сейчас конечно, а позже.

**Comment by ava57r** [comment]
а у тебя прям падало?
Думаю как под это дело тест написать...

**Comment by dmpas** [comment]
> а у тебя прям падало?

![default](https://user-images.githubusercontent.com/5665433/36351682-a3d49ad0-14be-11e8-91ce-11a5ece623a8.png)

сигсегв. Держи колстэк

**Comment by dmpas** [comment]
тупо вызвать `T_1CD::supplier_configs()`

**Comment by ava57r** [comment]
ммм
1. тестирую у себя выгрузку не той конфы
2. после багфикса поймал еще один сигсегв.

пошел разбираться.

**Comment by ava57r** [comment]
Во еще одна ошибка связана с тем что V8Catalog считает поток своим и пытается подчистить за собой.

**Comment by ava57r** [comment]
https://github.com/dmpas/tool1cd/blob/develop/tests/db838/db01/1Cv8.1CD что за конфа?

**Comment by dmpas** [comment]
> что за конфа?

"разработка конфигураций с нуля" :). Один справочник, расширение с обработкой. Без конфы поставщика, сохранённая конфигурация отличается от конфигурации БД

**Comment by ava57r** [comment]
>  что за конфа?
>
> "разработка конфигураций с нуля" :). Один справочник, расширение с обработкой. Без конфы 
> поставщика, сохранённая конфигурация отличается от конфигурации БД

пора редми к таким файлам писать
