### ISSUE TITLE
Сделать MemBlock нестатичным и добавить полем в T_1CD

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#226]
#224

**Comment by dmpas** [comment]
Это нужно для гуёвой версии, которая работает с несколькими открытыми базами одновременно.

**Comment by ava57r** [comment]
Тут надо потумкать.
В статических полях массив `MemBlock`'ов
Сам `MemBlock` представляет некое подобие связанного списка.
В статических полях содержаться указатели на начало и конец связанного списка

**Comment by dmpas** [comment]
чего тут тумкать? Был один связный список, станет много, без статических полей.

**Comment by ava57r** [comment]
Ну не скажи.
Если отдать список самому мемблоку, то получится мемблок владеет списом мемблоков, которые сами владеют списками мемблоков.

Надо сделать РаспределительМемблоков и от этого уже плясать.
