### ISSUE TITLE
Реализовать parse_flow с возвратом unique_ptr

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#241]

**Comment by ava57r** [comment]
@dmpas 
Есть скольский момент
`SkobkaTreeModel` хранит ссылку на `Tree`
Есть реализация метода

```c++
SkobkaTreeModel::rowCount(const QModelIndex &parent)

Tree *parentItem = static_cast<Tree*>(parent.internalPointer());
```

Это же cast внутреннего указателя из `SkobkaTreeModel` ?

**Comment by dmpas** [comment]
да, там в internalPointer хранится указатель на определённый узел дерева.

**Comment by ava57r** [comment]
Имеено узел? не на модель?

**Comment by dmpas** [comment]
именно здесь именно узел. На модель указатель получается просто через `model()`.

в Qt вообще всё построено на сырых указателях :(
