### ISSUE TITLE
Попытка сохранения файла основной конфигурации с кирилическим именем сохраняет с неверной кодировкой имя

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#263]

**Comment by dmpas** [comment]
а чо, консольная штука отрабатывает верно? мингв-шная сборка правильно отрабатывает?

**Comment by ava57r** [comment]
не тестил, написал на чем нашел багу

**Comment by dmpas** [comment]
ну просто ты плашку "гуй" повесил, а это не ошибка гуя, я думаю. ошибка либы.

**Comment by ava57r** [comment]
Скачал артифакты сборки, такая же петрушка под gui.
проблема тут
```c++
filename.toStdString()
```

**Comment by ava57r** [comment]
может тестов добавим?

**Comment by dmpas** [comment]
Тесты надо. Нет на них сейчас сил.

**Comment by ava57r** [comment]
А это мы не пофиксили?

**Comment by dmpas** [comment]
@andreevlex не помню. может, из-за тестов не закрываем до сих пор :)

**Comment by ava57r** [comment]
пойду проверю.

**Comment by ava57r** [comment]
Все норм
