### ISSUE TITLE
Открытие файла базы с кирилическими символами в пути выдает ошибку

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#266]
Пытаюсь открыть через GUI.
Выдается ошибка:

`Файл не является базой 1С (сигнатура не равна "1CDBMSV8")`

Ошибка преобразования из QString.

**Comment by ava57r** [comment]
Скачал артифакты сборки, такая же петрушка под gui.
проблема тут
```c++
filename.toStdString()
```

**Comment by ava57r** [comment]
Не умеем мы готовить `QString -> std::string`

**Comment by dmpas** [comment]
> Не умеем мы готовить QString -> std::string

дык его сам Qt должен уметь готовить..

**Comment by dmpas** [comment]
Есть обход: в т1сд_класс и всяких прочих классах принимать вместо/вместе `std::string` - `boost::filesystem::path`. а `path` в зависимости от места вызова инициализировать или из `std::string`, или из `QString::toStdWString()` - это сработало, надо только красиво доделать.

**Comment by ava57r** [comment]
может тестов добавим?

**Comment by dmpas** [comment]
Да, надо.
