### ISSUE TITLE
Ошибка выгрузки конфигурации из хранилища версии 7 по ключу -drc

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#66]
```log
  1 Чтение таблиц 0
  2 Чтение таблиц 10
  3 База данных 1CD открыта
  4   Файл = /home/ubuntu/dev-pro/testctool1cd/хранилище/1cv8ddb.1CD
  5   Версия базы = 8.3.8.0
  6   Locale = ru_RU
  7   Режим = Редактирование
  8   Количество таблиц = 10
  9 Чтение индекса
 10 
 11 Чтение индекса
 12 
 13 Чтение индекса
 14 
 15 Не найден файл
 16   Файл = /home/ubuntu/dev-pro/testctool1cd/хранилище/1cv8ddb.1CD/data/objects/d77c497e1adcf0d71d0daeb2dad35a43c2b7a6
 17   Таблица = HISTORY
 18   Объект = 9f805d9a-70bf-474b-9b1f-ca1fc5b9839b
 19   Версия = 2
 20 Ошибка чтения объекта конфигурации
 21   Таблица = HISTORY
 22   Объект = 9f805d9a-70bf-474b-9b1f-ca1fc5b9839b
 23   Версия = 2
 24 Сохранение конфигурации хранилища завершено.
 25   Файл = /home/ubuntu/dev-pro/testctool1cd/1cvbddb_dep/v2.cf
```
[depot_ver7.zip](https://github.com/dmpas/tool1cd/files/1225871/depot_ver7.zip)

**Comment by dmpas** [comment]
у меня сработало.

**Comment by dmpas** [comment]
Параметры запуска проверь

**Comment by ava57r** [comment]
У меня тоже пишет, что выгрузка прошла, но загрузить такую конфигурацию в конфигураторе не получается, пишет "Нарушена целостность ..."

выгружаю последнюю версию
`-drc 0`
там в каталоге data/objects/cb лежит файл необходимый, а поиск идет в каталоге data/objects
`cb` присуствует в переменной перед получением имени вот так `cbd77c497e1adcf0d71d0daeb2dad35a43c2b7a6`
В коде используется имя без этого префикса.

**Comment by dmpas** [comment]
У меня даже ошибки не выдало, которая у тебя.

**Comment by ava57r** [comment]
а тестил на моем файле? Я его приложил к задаче.

**Comment by dmpas** [comment]
да, на нём и тестил.

**Comment by ava57r** [comment]
а выполнение на строку https://github.com/dmpas/tool1cd/blob/develop/src/ctool1cd/Class_1CD.cpp#L2919 попадает?
чему равен `boost::filesystem::path current_object_path`

**Comment by dmpas** [comment]
Дома буду - гляну.

**Comment by ava57r** [comment]
Поправил, теперь все без ошибок, но только для версии 7.
У кого-нибудь есть версия 6?

**Comment by dmpas** [comment]
твой коммит не объясняет, почему у меня на твоих данных сработало.

**Comment by dmpas** [comment]
> https://github.com/dmpas/tool1cd/blob/develop/src/ctool1cd/Class_1CD.cpp#L2919 

воткнул в ту строчку `std::cout << "I'm here!" << std::endl;`

```
dmpas@dmpas-asus:~/workspace/tool1cd/build_dir
$ bin/ctool1cd -drc 0 . ~/Загрузки/хранилище/1cv8ddb.1CD 
Чтение таблиц 0
Чтение таблиц 10
Чтение индекса 

Чтение индекса 

Чтение индекса 

I'm here!
```

то есть, доходит. Свежесобранный девелоп.

**Comment by ava57r** [comment]
Неа, я привел инфу из файла логов, а вот там как раз ошибка. 
Проверь пожалуйста файл логов.

**Comment by dmpas** [comment]
> Проверь пожалуйста файл логов.

Ха! а там есть ошибка!

**Comment by ava57r** [comment]
Вот.
Необходима версия хранилища 6.
Если изменилась структура каталогов, то изменений будет больше.

**Comment by ava57r** [comment]
Создал хранилище версии 6 в 1С:Предприятие 8.3 (8.3.4.365)
Проверил выгрузку конфигурации и загрузку ее в чистую базу.
[depot_ver6.zip](https://github.com/dmpas/tool1cd/files/1261131/depot_ver6.zip)

**Comment by ava57r** [comment]
Архив depot_ver6.zip не полный. Вечером приложу корректный.

**Comment by ava57r** [comment]
[depot_ver6.zip](https://github.com/dmpas/tool1cd/files/1264281/depot_ver6.zip)
