### ISSUE TITLE
Не выгружаются блобы для хранилищ версий 6 и 7

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#73]
Все поля на блобы = `<OBJDATA>{NULL}</OBJDATA>` 
[depotv6.zip](https://github.com/dmpas/tool1cd/files/1334805/depotv6.zip)
[depotv7.zip](https://github.com/dmpas/tool1cd/files/1334807/depotv7.zip)

надо протестировать

**Comment by ava57r** [comment]
вызываю так 
```sh
-ex /home/dev-pro/tool1cd/tests/depotv6/xml HISTORY;EXTERNALS /home/dev-pro/tool1cd/tests/depotv6/depot/1cv8ddb.1CD -bf yes -pb yes
```

**Comment by dmpas** [comment]
они там точно должны быть?

PS я вот со страхом смотрю на каталог `pack` - уж не гитовский ли это pack-файл?..

**Comment by ava57r** [comment]
Не знаю должны ли быть.
GUID' ы есть вероятно и блобы должны быть. 
Поразбираюсь может изменился принцип хранения блобов.

Организация каталогов похожа на гитовые) особенно data/objects == .git/objects

**Comment by dmpas** [comment]
вот мне тут на днях на глаза попалось хранилище, где в `data` пусто, зато есть `pck` и `idx` - прям, как в гите. Так что я на досуге покуриваю книжку git-pro, чего и тебе советую :) ну и пару раз собрать ручками libgit2 - тоже приключение, если под винду.

**Comment by ava57r** [comment]
По методу save_depot_config видно, что с 6 версии хранилища блобы, на которые ссылаются записи таблиц HISTORY и EXTERNALS хранятся в каталоге `data/objects`. 
Имена файлов в objects - это хэши.
В HISTORY и EXTERNALS появилась запись для каждого объекта.
Например 
```xml
<DATAHASH>28ee280565c795ac762e90a756e921ea63d618e3</DATAHASH>
```
нужный файл лежит в `data/objects/28/ee280565c795ac762e90a756e921ea63d618e3`

**Comment by ava57r** [comment]
в итоге нам нужна функциональность по выгрузки блобов и парсингу их из хранилищ выше 5 версии?

**Comment by dmpas** [comment]
Скорее всего понадобится, но не в первую очередь. Так что задачку оставь.

**Comment by dmpas** [comment]
Эту пока закроем. Блоба в самой базе нет - выгружать не надо.
