### ISSUE TITLE
Реализовать метод CreateGUID

### ISSUE THREAD

**Issue by ava57r** [e8tools/tool1cd#74]

**Comment by dmpas** [comment]
Зачем?

**Comment by ava57r** [comment]
Предлагаешь отказаться от его использования?

**Comment by dmpas** [comment]
В смысле, он у нас уже есть, только не работает? Тогда надо :)

**Comment by ava57r** [comment]
Да в теле стоит `TODO` и все.
Всегда формируется пустой GUID.
Используется при выгрузке конфигурации по ключу DumpDepotConfig
1с-ку устраивает и пустой GUID, но ведь для чего-то он там нужен)
