### ISSUE TITLE
Перевести `IMessageRegistration` на вариативный шаблон.

### ISSUE THREAD

**Issue by dmpas** [e8tools/tool1cd#89]

**Comment by ava57r** [comment]
При распаковке пакета порядок аргументов не определен и они будут произвольном порядке
конструкция `const String& parname1, const String& par1` может не прокатить

**Comment by dmpas** [comment]
Можно std::pair попробовать

**Comment by ava57r** [comment]
а может класс Message?

**Comment by dmpas** [comment]
> а может класс Message?

Возможно...
